# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shuafenshou' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for shuafenshou
    pod 'UMCCommon'
    #pod 'UMCSecurityPlugins'
    pod 'UMCAnalytics'
    pod 'UMCPush'
    # 集成微信(完整版14.4M)
    pod 'UMCShare/Social/WeChat'
    # 集成QQ/QZone/TIM(完整版7.6M)
    pod 'UMCShare/Social/QQ'
    # 集成支付宝
    pod 'UMCShare/Social/AlipayShare'    


  target 'shuafenshouTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

